// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNa1nZCsb6tzdsHkUdm43i2fsh64R92IM',
    appId: '1:448301698868:web:96590fc1b2584b3f0edf61',
    messagingSenderId: '448301698868',
    projectId: 'mynotes-flutter-rgala',
    authDomain: 'mynotes-flutter-rgala.firebaseapp.com',
    storageBucket: 'mynotes-flutter-rgala.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQfOxhj-FT0cWt5uteBMmNllax5x6kDY',
    appId: '1:448301698868:android:24e6adb58097eadf0edf61',
    messagingSenderId: '448301698868',
    projectId: 'mynotes-flutter-rgala',
    storageBucket: 'mynotes-flutter-rgala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_n3Nyd5mlb4_UCPUdRBFUv6LP4I80l7c',
    appId: '1:448301698868:ios:ac5ca4db723779200edf61',
    messagingSenderId: '448301698868',
    projectId: 'mynotes-flutter-rgala',
    storageBucket: 'mynotes-flutter-rgala.appspot.com',
    iosClientId: '448301698868-a0q3au08cc49shsvu9hji69qv17dggk0.apps.googleusercontent.com',
    iosBundleId: 'com.rgala.mynotes',
  );
}
